framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true


    # Tried adding Redis here but it does not seem to work and I can not work out how to
    # change it in a reasonable amount of time.
    # config/packages/framework.yaml
#    framework:
#        session:
#            handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler